nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://192.168.1.253:8080']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['http://192.168.1.253:8080']
